name: documentar

on:
  push:
    branches:
      - 'main'

jobs:
  create-html-doc:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: create html documentation
        id: merge-code-doc
        run: bash doc.sh
      - uses: docker://pandoc/latex:3.5
        with:
          args: salida.md --output=archivos-mergeados.html
      - name: release html
        uses: softprops/action-gh-release@v2
        with:
          file: archivos-mergeados.html
      - name: remove markdown
        run: rm salida.md


