name: documentar

on:
  push:
    tags:
      - 'release-v*'

jobs:
  create-html-doc:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: create html documentation
        id: merge-code-doc
        run: bash doc.sh
      - uses: docker://pandoc/latex:3.5
        with:
          args: salida.md --output=archivos-mergeados.html
      - name: release html
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: archivos-mergeados.html
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      - name: remove markdown
        run: rm salida.md


